### ISSUE TITLE
IsoZero CLI crashes at launch on MacOS 14.3

### ISSUE THREAD

**Issue by leeirvinekezzico** [iso-ai/isozero_examples#2]
**To Reproduce**

1. create a virtual environment and activate

```
python -m venv venv
source venv/bin/activate
```

2. install isozero into the virtual environment

```
pip install isozero
```

3. run isozero

```
isozero
```

**Expected behavior**

Isozero command line tool should exit gracefully or process command arguments.

**Additional context**
Terminal output. with Stacktrace.

```
(venv) lee@starlight kezzico_zeroshot $ isozero
/Users/lee/src/ai/kezzico_zeroshot/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/lee/src/ai/kezzico_zeroshot/venv/bin/isozero", line 5, in <module>
    from isozero.cli import main
  File "/Users/lee/src/ai/kezzico_zeroshot/venv/lib/python3.9/site-packages/isozero/__init__.py", line 1, in <module>
    from .reason_sim import *
  File "/Users/lee/src/ai/kezzico_zeroshot/venv/lib/python3.9/site-packages/isozero/reason_sim/__init__.py", line 6, in <module>
    from .document_search import DocumentSearch
  File "/Users/lee/src/ai/kezzico_zeroshot/venv/lib/python3.9/site-packages/isozero/reason_sim/document_search.py", line 2, in <module>
    from sklearn.feature_extraction.text import TfidfVectorizer
  File "/Users/lee/src/ai/kezzico_zeroshot/venv/lib/python3.9/site-packages/sklearn/__init__.py", line 84, in <module>
    from .base import clone
  File "/Users/lee/src/ai/kezzico_zeroshot/venv/lib/python3.9/site-packages/sklearn/base.py", line 19, in <module>
    from .utils._estimator_html_repr import _HTMLDocumentationLinkMixin, estimator_html_repr
  File "/Users/lee/src/ai/kezzico_zeroshot/venv/lib/python3.9/site-packages/sklearn/utils/__init__.py", line 11, in <module>
    from ._chunking import gen_batches, gen_even_slices
  File "/Users/lee/src/ai/kezzico_zeroshot/venv/lib/python3.9/site-packages/sklearn/utils/_chunking.py", line 8, in <module>
    from ._param_validation import Interval, validate_params
  File "/Users/lee/src/ai/kezzico_zeroshot/venv/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 14, in <module>
    from .validation import _is_arraylike_not_scalar
  File "/Users/lee/src/ai/kezzico_zeroshot/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 26, in <module>
    from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace
  File "/Users/lee/src/ai/kezzico_zeroshot/venv/lib/python3.9/site-packages/sklearn/utils/_array_api.py", line 11, in <module>
    from .fixes import parse_version
  File "/Users/lee/src/ai/kezzico_zeroshot/venv/lib/python3.9/site-packages/sklearn/utils/fixes.py", line 21, in <module>
    import scipy.stats
  File "/Users/lee/src/ai/kezzico_zeroshot/venv/lib/python3.9/site-packages/scipy/stats/__init__.py", line 606, in <module>
    from ._stats_py import *
  File "/Users/lee/src/ai/kezzico_zeroshot/venv/lib/python3.9/site-packages/scipy/stats/_stats_py.py", line 49, in <module>
    from . import distributions
  File "/Users/lee/src/ai/kezzico_zeroshot/venv/lib/python3.9/site-packages/scipy/stats/distributions.py", line 10, in <module>
    from . import _continuous_distns
  File "/Users/lee/src/ai/kezzico_zeroshot/venv/lib/python3.9/site-packages/scipy/stats/_continuous_distns.py", line 33, in <module>
    import scipy.stats._boost as _boost
  File "/Users/lee/src/ai/kezzico_zeroshot/venv/lib/python3.9/site-packages/scipy/stats/_boost/__init__.py", line 25, in <module>
    from scipy.stats._boost.ncf_ufunc import (
  File "<frozen importlib._bootstrap>", line 398, in parent
KeyboardInterrupt

(venv) lee@starlight kezzico_zeroshot $  ls
venv
(venv) lee@starlight kezzico_zeroshot $ python 
(venv) lee@starlight kezzico_zeroshot $ pip 
(venv) lee@starlight kezzico_zeroshot $ pip freeze > requirements.txt
(venv) lee@starlight kezzico_zeroshot $ ls
requirements.txt venv
(venv) lee@starlight kezzico_zeroshot $ cat requirements.txt 
annotated-types==0.7.0
anthropic==0.38.0
anyio==4.6.2.post1
attrs==24.2.0
beautifulsoup4==4.12.3
certifi==2024.8.30
charset-normalizer==3.4.0
contourpy==1.3.0
cycler==0.12.1
distro==1.9.0
exceptiongroup==1.2.2
filelock==3.16.1
fonttools==4.54.1
fsspec==2024.10.0
h11==0.14.0
httpcore==1.0.6
httpx==0.27.2
huggingface-hub==0.26.2
idna==3.10
importlib_resources==6.4.5
isozero==0.1.0
Jinja2==3.1.4
jiter==0.7.0
joblib==1.4.2
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
kiwisolver==1.4.7
MarkupSafe==3.0.2
matplotlib==3.9.2
mpmath==1.3.0
networkx==3.2.1
numpy==2.0.2
openai==1.53.0
packaging==24.1
pandas==2.2.3
pillow==11.0.0
pydantic==2.9.2
pydantic_core==2.23.4
pyparsing==3.2.0
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
pytz==2024.2
PyYAML==6.0.2
referencing==0.35.1
regex==2024.9.11
requests==2.32.3
rpds-py==0.20.1
safetensors==0.4.5
scikit-learn==1.5.2
scipy==1.13.1
six==1.16.0
sniffio==1.3.1
soupsieve==2.6
sympy==1.13.1
threadpoolctl==3.5.0
tokenizers==0.20.1
torch==2.5.1
tqdm==4.66.6
transformers==4.46.1
typing_extensions==4.12.2
tzdata==2024.2
urllib3==2.2.3
zipp==3.20.2
```

**Comment by leeirvinekezzico** [comment]
I resolved the error by installing tiktoken into the virtual environment

```
pip install tiktoken
```

However, this leads me to a second issue.

**Output**

```
(venv) lee@starlight kezzico_zeroshot $ isozero                                                   
/Users/lee/src/ai/kezzico_zeroshot/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/lee/src/ai/kezzico_zeroshot/venv/bin/isozero", line 5, in <module>
    from isozero.cli import main
ModuleNotFoundError: No module named 'isozero.cli'
```
